{
 "title": "Cyber Mirage - System Overview",
 "tags": [
  "cyber_mirage",
  "honeypot"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"cyber_mirage.*\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"cyber_mirage.*\"})"
    }
   ]
  },
  {
   "title": "Network Traffic (Receive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"cyber_mirage.*\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}